# Generated by Django 3.2.18 on 2023-03-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='auth_key',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='endpoint_url',
            field=models.CharField(default=None, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='p256dh_key',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
