# Generated by Django 3.2.18 on 2023-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='endpoint_url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
