# Generated by Django 3.2.18 on 2023-03-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_alter_subscriber_endpoint_url'),
        ('subscribers', '0002_auto_20230306_0802'),
    ]

    operations = [
    ]
