# Generated by Django 3.2.18 on 2023-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_merge_20230307_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='endpoint_url',
            field=models.CharField(default=None, max_length=500, unique=True),
        ),
    ]
